# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Zynq\Ui\MainWindow.ui'
#
# Created: Tue Oct 24 09:34:14 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1553, 914)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.m_paraSetWidget = ParaSetWidget(self.centralWidget)
        self.m_paraSetWidget.setGeometry(QtCore.QRect(250, 750, 841, 141))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_paraSetWidget.sizePolicy().hasHeightForWidth())
        self.m_paraSetWidget.setSizePolicy(sizePolicy)
        self.m_paraSetWidget.setObjectName(_fromUtf8("m_paraSetWidget"))
        self.m_aScanWidget = AScanWidget(self.centralWidget)
        self.m_aScanWidget.setGeometry(QtCore.QRect(250, 30, 431, 221))
        self.m_aScanWidget.setObjectName(_fromUtf8("m_aScanWidget"))
        self.m_parseToolWidget = ParseToolWidget(self.centralWidget)
        self.m_parseToolWidget.setGeometry(QtCore.QRect(10, 10, 221, 461))
        self.m_parseToolWidget.setObjectName(_fromUtf8("m_parseToolWidget"))
        self.layoutWidget = QtGui.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(680, 10, 88, 22))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.m_chanoChosen_2 = QtGui.QComboBox(self.layoutWidget)
        self.m_chanoChosen_2.setObjectName(_fromUtf8("m_chanoChosen_2"))
        self.m_chanoChosen_2.addItem(_fromUtf8(""))
        self.m_chanoChosen_2.addItem(_fromUtf8(""))
        self.m_chanoChosen_2.addItem(_fromUtf8(""))
        self.m_chanoChosen_2.addItem(_fromUtf8(""))
        self.m_chanoChosen_2.addItem(_fromUtf8(""))
        self.m_chanoChosen_2.addItem(_fromUtf8(""))
        self.m_chanoChosen_2.addItem(_fromUtf8(""))
        self.m_chanoChosen_2.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.m_chanoChosen_2)
        self.m_aScanWidget_2 = AScanWidget(self.centralWidget)
        self.m_aScanWidget_2.setGeometry(QtCore.QRect(680, 30, 431, 221))
        self.m_aScanWidget_2.setObjectName(_fromUtf8("m_aScanWidget_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(1110, 10, 88, 22))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.m_chanoChosen_3 = QtGui.QComboBox(self.layoutWidget_2)
        self.m_chanoChosen_3.setObjectName(_fromUtf8("m_chanoChosen_3"))
        self.m_chanoChosen_3.addItem(_fromUtf8(""))
        self.m_chanoChosen_3.addItem(_fromUtf8(""))
        self.m_chanoChosen_3.addItem(_fromUtf8(""))
        self.m_chanoChosen_3.addItem(_fromUtf8(""))
        self.m_chanoChosen_3.addItem(_fromUtf8(""))
        self.m_chanoChosen_3.addItem(_fromUtf8(""))
        self.m_chanoChosen_3.addItem(_fromUtf8(""))
        self.m_chanoChosen_3.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.m_chanoChosen_3)
        self.m_aScanWidget_3 = AScanWidget(self.centralWidget)
        self.m_aScanWidget_3.setGeometry(QtCore.QRect(1110, 30, 431, 221))
        self.m_aScanWidget_3.setObjectName(_fromUtf8("m_aScanWidget_3"))
        self.layoutWidget_5 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(250, 250, 88, 22))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.m_chanoChosen_6 = QtGui.QComboBox(self.layoutWidget_5)
        self.m_chanoChosen_6.setObjectName(_fromUtf8("m_chanoChosen_6"))
        self.m_chanoChosen_6.addItem(_fromUtf8(""))
        self.m_chanoChosen_6.addItem(_fromUtf8(""))
        self.m_chanoChosen_6.addItem(_fromUtf8(""))
        self.m_chanoChosen_6.addItem(_fromUtf8(""))
        self.m_chanoChosen_6.addItem(_fromUtf8(""))
        self.m_chanoChosen_6.addItem(_fromUtf8(""))
        self.m_chanoChosen_6.addItem(_fromUtf8(""))
        self.m_chanoChosen_6.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.m_chanoChosen_6)
        self.layoutWidget_4 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(1110, 250, 88, 22))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.m_chanoChosen_5 = QtGui.QComboBox(self.layoutWidget_4)
        self.m_chanoChosen_5.setObjectName(_fromUtf8("m_chanoChosen_5"))
        self.m_chanoChosen_5.addItem(_fromUtf8(""))
        self.m_chanoChosen_5.addItem(_fromUtf8(""))
        self.m_chanoChosen_5.addItem(_fromUtf8(""))
        self.m_chanoChosen_5.addItem(_fromUtf8(""))
        self.m_chanoChosen_5.addItem(_fromUtf8(""))
        self.m_chanoChosen_5.addItem(_fromUtf8(""))
        self.m_chanoChosen_5.addItem(_fromUtf8(""))
        self.m_chanoChosen_5.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.m_chanoChosen_5)
        self.m_aScanWidget_5 = AScanWidget(self.centralWidget)
        self.m_aScanWidget_5.setGeometry(QtCore.QRect(680, 270, 431, 221))
        self.m_aScanWidget_5.setObjectName(_fromUtf8("m_aScanWidget_5"))
        self.m_aScanWidget_6 = AScanWidget(self.centralWidget)
        self.m_aScanWidget_6.setGeometry(QtCore.QRect(250, 270, 431, 221))
        self.m_aScanWidget_6.setObjectName(_fromUtf8("m_aScanWidget_6"))
        self.m_aScanWidget_4 = AScanWidget(self.centralWidget)
        self.m_aScanWidget_4.setGeometry(QtCore.QRect(1110, 270, 431, 221))
        self.m_aScanWidget_4.setObjectName(_fromUtf8("m_aScanWidget_4"))
        self.layoutWidget_3 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(680, 250, 88, 22))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.m_chanoChosen_4 = QtGui.QComboBox(self.layoutWidget_3)
        self.m_chanoChosen_4.setObjectName(_fromUtf8("m_chanoChosen_4"))
        self.m_chanoChosen_4.addItem(_fromUtf8(""))
        self.m_chanoChosen_4.addItem(_fromUtf8(""))
        self.m_chanoChosen_4.addItem(_fromUtf8(""))
        self.m_chanoChosen_4.addItem(_fromUtf8(""))
        self.m_chanoChosen_4.addItem(_fromUtf8(""))
        self.m_chanoChosen_4.addItem(_fromUtf8(""))
        self.m_chanoChosen_4.addItem(_fromUtf8(""))
        self.m_chanoChosen_4.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.m_chanoChosen_4)
        self.m_aScanWidget_7 = AScanWidget(self.centralWidget)
        self.m_aScanWidget_7.setGeometry(QtCore.QRect(1110, 510, 431, 221))
        self.m_aScanWidget_7.setObjectName(_fromUtf8("m_aScanWidget_7"))
        self.m_aScanWidget_8 = AScanWidget(self.centralWidget)
        self.m_aScanWidget_8.setGeometry(QtCore.QRect(680, 510, 431, 221))
        self.m_aScanWidget_8.setObjectName(_fromUtf8("m_aScanWidget_8"))
        self.layoutWidget_6 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget_6.setGeometry(QtCore.QRect(680, 490, 88, 22))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.m_chanoChosen_7 = QtGui.QComboBox(self.layoutWidget_6)
        self.m_chanoChosen_7.setObjectName(_fromUtf8("m_chanoChosen_7"))
        self.m_chanoChosen_7.addItem(_fromUtf8(""))
        self.m_chanoChosen_7.addItem(_fromUtf8(""))
        self.m_chanoChosen_7.addItem(_fromUtf8(""))
        self.m_chanoChosen_7.addItem(_fromUtf8(""))
        self.m_chanoChosen_7.addItem(_fromUtf8(""))
        self.m_chanoChosen_7.addItem(_fromUtf8(""))
        self.m_chanoChosen_7.addItem(_fromUtf8(""))
        self.m_chanoChosen_7.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.m_chanoChosen_7)
        self.layoutWidget_7 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget_7.setGeometry(QtCore.QRect(1110, 490, 88, 22))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.layoutWidget_7)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.m_chanoChosen_8 = QtGui.QComboBox(self.layoutWidget_7)
        self.m_chanoChosen_8.setObjectName(_fromUtf8("m_chanoChosen_8"))
        self.m_chanoChosen_8.addItem(_fromUtf8(""))
        self.m_chanoChosen_8.addItem(_fromUtf8(""))
        self.m_chanoChosen_8.addItem(_fromUtf8(""))
        self.m_chanoChosen_8.addItem(_fromUtf8(""))
        self.m_chanoChosen_8.addItem(_fromUtf8(""))
        self.m_chanoChosen_8.addItem(_fromUtf8(""))
        self.m_chanoChosen_8.addItem(_fromUtf8(""))
        self.m_chanoChosen_8.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.m_chanoChosen_8)
        self.m_aScanWidget_9 = AScanWidget(self.centralWidget)
        self.m_aScanWidget_9.setGeometry(QtCore.QRect(250, 510, 431, 221))
        self.m_aScanWidget_9.setObjectName(_fromUtf8("m_aScanWidget_9"))
        self.layoutWidget_8 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget_8.setGeometry(QtCore.QRect(250, 490, 88, 22))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_9 = QtGui.QLabel(self.layoutWidget_8)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_9.addWidget(self.label_9)
        self.m_chanoChosen_9 = QtGui.QComboBox(self.layoutWidget_8)
        self.m_chanoChosen_9.setObjectName(_fromUtf8("m_chanoChosen_9"))
        self.m_chanoChosen_9.addItem(_fromUtf8(""))
        self.m_chanoChosen_9.addItem(_fromUtf8(""))
        self.m_chanoChosen_9.addItem(_fromUtf8(""))
        self.m_chanoChosen_9.addItem(_fromUtf8(""))
        self.m_chanoChosen_9.addItem(_fromUtf8(""))
        self.m_chanoChosen_9.addItem(_fromUtf8(""))
        self.m_chanoChosen_9.addItem(_fromUtf8(""))
        self.m_chanoChosen_9.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.m_chanoChosen_9)
        self.widget = QtGui.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(250, 10, 88, 22))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.m_chanoChosen = QtGui.QComboBox(self.widget)
        self.m_chanoChosen.setObjectName(_fromUtf8("m_chanoChosen"))
        self.m_chanoChosen.addItem(_fromUtf8(""))
        self.m_chanoChosen.addItem(_fromUtf8(""))
        self.m_chanoChosen.addItem(_fromUtf8(""))
        self.m_chanoChosen.addItem(_fromUtf8(""))
        self.m_chanoChosen.addItem(_fromUtf8(""))
        self.m_chanoChosen.addItem(_fromUtf8(""))
        self.m_chanoChosen.addItem(_fromUtf8(""))
        self.m_chanoChosen.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.m_chanoChosen)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "显示通道", None))
        self.m_chanoChosen_2.setItemText(0, _translate("MainWindow", "1", None))
        self.m_chanoChosen_2.setItemText(1, _translate("MainWindow", "2", None))
        self.m_chanoChosen_2.setItemText(2, _translate("MainWindow", "3", None))
        self.m_chanoChosen_2.setItemText(3, _translate("MainWindow", "4", None))
        self.m_chanoChosen_2.setItemText(4, _translate("MainWindow", "5", None))
        self.m_chanoChosen_2.setItemText(5, _translate("MainWindow", "6", None))
        self.m_chanoChosen_2.setItemText(6, _translate("MainWindow", "7", None))
        self.m_chanoChosen_2.setItemText(7, _translate("MainWindow", "8", None))
        self.label_3.setText(_translate("MainWindow", "显示通道", None))
        self.m_chanoChosen_3.setItemText(0, _translate("MainWindow", "1", None))
        self.m_chanoChosen_3.setItemText(1, _translate("MainWindow", "2", None))
        self.m_chanoChosen_3.setItemText(2, _translate("MainWindow", "3", None))
        self.m_chanoChosen_3.setItemText(3, _translate("MainWindow", "4", None))
        self.m_chanoChosen_3.setItemText(4, _translate("MainWindow", "5", None))
        self.m_chanoChosen_3.setItemText(5, _translate("MainWindow", "6", None))
        self.m_chanoChosen_3.setItemText(6, _translate("MainWindow", "7", None))
        self.m_chanoChosen_3.setItemText(7, _translate("MainWindow", "8", None))
        self.label_6.setText(_translate("MainWindow", "显示通道", None))
        self.m_chanoChosen_6.setItemText(0, _translate("MainWindow", "1", None))
        self.m_chanoChosen_6.setItemText(1, _translate("MainWindow", "2", None))
        self.m_chanoChosen_6.setItemText(2, _translate("MainWindow", "3", None))
        self.m_chanoChosen_6.setItemText(3, _translate("MainWindow", "4", None))
        self.m_chanoChosen_6.setItemText(4, _translate("MainWindow", "5", None))
        self.m_chanoChosen_6.setItemText(5, _translate("MainWindow", "6", None))
        self.m_chanoChosen_6.setItemText(6, _translate("MainWindow", "7", None))
        self.m_chanoChosen_6.setItemText(7, _translate("MainWindow", "8", None))
        self.label_5.setText(_translate("MainWindow", "显示通道", None))
        self.m_chanoChosen_5.setItemText(0, _translate("MainWindow", "1", None))
        self.m_chanoChosen_5.setItemText(1, _translate("MainWindow", "2", None))
        self.m_chanoChosen_5.setItemText(2, _translate("MainWindow", "3", None))
        self.m_chanoChosen_5.setItemText(3, _translate("MainWindow", "4", None))
        self.m_chanoChosen_5.setItemText(4, _translate("MainWindow", "5", None))
        self.m_chanoChosen_5.setItemText(5, _translate("MainWindow", "6", None))
        self.m_chanoChosen_5.setItemText(6, _translate("MainWindow", "7", None))
        self.m_chanoChosen_5.setItemText(7, _translate("MainWindow", "8", None))
        self.label_4.setText(_translate("MainWindow", "显示通道", None))
        self.m_chanoChosen_4.setItemText(0, _translate("MainWindow", "1", None))
        self.m_chanoChosen_4.setItemText(1, _translate("MainWindow", "2", None))
        self.m_chanoChosen_4.setItemText(2, _translate("MainWindow", "3", None))
        self.m_chanoChosen_4.setItemText(3, _translate("MainWindow", "4", None))
        self.m_chanoChosen_4.setItemText(4, _translate("MainWindow", "5", None))
        self.m_chanoChosen_4.setItemText(5, _translate("MainWindow", "6", None))
        self.m_chanoChosen_4.setItemText(6, _translate("MainWindow", "7", None))
        self.m_chanoChosen_4.setItemText(7, _translate("MainWindow", "8", None))
        self.label_7.setText(_translate("MainWindow", "显示通道", None))
        self.m_chanoChosen_7.setItemText(0, _translate("MainWindow", "1", None))
        self.m_chanoChosen_7.setItemText(1, _translate("MainWindow", "2", None))
        self.m_chanoChosen_7.setItemText(2, _translate("MainWindow", "3", None))
        self.m_chanoChosen_7.setItemText(3, _translate("MainWindow", "4", None))
        self.m_chanoChosen_7.setItemText(4, _translate("MainWindow", "5", None))
        self.m_chanoChosen_7.setItemText(5, _translate("MainWindow", "6", None))
        self.m_chanoChosen_7.setItemText(6, _translate("MainWindow", "7", None))
        self.m_chanoChosen_7.setItemText(7, _translate("MainWindow", "8", None))
        self.label_8.setText(_translate("MainWindow", "显示通道", None))
        self.m_chanoChosen_8.setItemText(0, _translate("MainWindow", "1", None))
        self.m_chanoChosen_8.setItemText(1, _translate("MainWindow", "2", None))
        self.m_chanoChosen_8.setItemText(2, _translate("MainWindow", "3", None))
        self.m_chanoChosen_8.setItemText(3, _translate("MainWindow", "4", None))
        self.m_chanoChosen_8.setItemText(4, _translate("MainWindow", "5", None))
        self.m_chanoChosen_8.setItemText(5, _translate("MainWindow", "6", None))
        self.m_chanoChosen_8.setItemText(6, _translate("MainWindow", "7", None))
        self.m_chanoChosen_8.setItemText(7, _translate("MainWindow", "8", None))
        self.label_9.setText(_translate("MainWindow", "显示通道", None))
        self.m_chanoChosen_9.setItemText(0, _translate("MainWindow", "1", None))
        self.m_chanoChosen_9.setItemText(1, _translate("MainWindow", "2", None))
        self.m_chanoChosen_9.setItemText(2, _translate("MainWindow", "3", None))
        self.m_chanoChosen_9.setItemText(3, _translate("MainWindow", "4", None))
        self.m_chanoChosen_9.setItemText(4, _translate("MainWindow", "5", None))
        self.m_chanoChosen_9.setItemText(5, _translate("MainWindow", "6", None))
        self.m_chanoChosen_9.setItemText(6, _translate("MainWindow", "7", None))
        self.m_chanoChosen_9.setItemText(7, _translate("MainWindow", "8", None))
        self.label.setText(_translate("MainWindow", "显示通道", None))
        self.m_chanoChosen.setItemText(0, _translate("MainWindow", "1", None))
        self.m_chanoChosen.setItemText(1, _translate("MainWindow", "2", None))
        self.m_chanoChosen.setItemText(2, _translate("MainWindow", "3", None))
        self.m_chanoChosen.setItemText(3, _translate("MainWindow", "4", None))
        self.m_chanoChosen.setItemText(4, _translate("MainWindow", "5", None))
        self.m_chanoChosen.setItemText(5, _translate("MainWindow", "6", None))
        self.m_chanoChosen.setItemText(6, _translate("MainWindow", "7", None))
        self.m_chanoChosen.setItemText(7, _translate("MainWindow", "8", None))

from ScanWidget import AScanWidget
from ParaSetWidget import ParaSetWidget
from ParseToolWidget import ParseToolWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

