# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Zynq\Ui\ParaSetWidget.ui'
#
# Created: Sat Sep 23 22:47:50 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ParaSetWidget(object):
    def setupUi(self, ParaSetWidget):
        ParaSetWidget.setObjectName(_fromUtf8("ParaSetWidget"))
        ParaSetWidget.resize(258, 468)
        self.widget = QtGui.QWidget(ParaSetWidget)
        self.widget.setGeometry(QtCore.QRect(10, 11, 231, 431))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.m_chanNo = QtGui.QComboBox(self.widget)
        self.m_chanNo.setObjectName(_fromUtf8("m_chanNo"))
        self.m_chanNo.addItem(_fromUtf8(""))
        self.m_chanNo.addItem(_fromUtf8(""))
        self.m_chanNo.addItem(_fromUtf8(""))
        self.m_chanNo.addItem(_fromUtf8(""))
        self.m_chanNo.addItem(_fromUtf8(""))
        self.m_chanNo.addItem(_fromUtf8(""))
        self.m_chanNo.addItem(_fromUtf8(""))
        self.m_chanNo.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.m_chanNo)
        self.horizontalLayout_11.addLayout(self.horizontalLayout)
        self.m_chanChecked = QtGui.QCheckBox(self.widget)
        self.m_chanChecked.setObjectName(_fromUtf8("m_chanChecked"))
        self.horizontalLayout_11.addWidget(self.m_chanChecked)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.m_eVoltage = QtGui.QDoubleSpinBox(self.widget)
        self.m_eVoltage.setObjectName(_fromUtf8("m_eVoltage"))
        self.horizontalLayout_7.addWidget(self.m_eVoltage)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.m_sampleLen = QtGui.QDoubleSpinBox(self.widget)
        self.m_sampleLen.setObjectName(_fromUtf8("m_sampleLen"))
        self.horizontalLayout_10.addWidget(self.m_sampleLen)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.m_gain = QtGui.QDoubleSpinBox(self.widget)
        self.m_gain.setObjectName(_fromUtf8("m_gain"))
        self.horizontalLayout_8.addWidget(self.m_gain)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_14.addWidget(self.label_11)
        self.m_recvChanNo = QtGui.QComboBox(self.widget)
        self.m_recvChanNo.setObjectName(_fromUtf8("m_recvChanNo"))
        self.m_recvChanNo.addItem(_fromUtf8(""))
        self.m_recvChanNo.addItem(_fromUtf8(""))
        self.m_recvChanNo.addItem(_fromUtf8(""))
        self.m_recvChanNo.addItem(_fromUtf8(""))
        self.m_recvChanNo.addItem(_fromUtf8(""))
        self.m_recvChanNo.addItem(_fromUtf8(""))
        self.m_recvChanNo.addItem(_fromUtf8(""))
        self.m_recvChanNo.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.m_recvChanNo)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.m_sonicV = QtGui.QDoubleSpinBox(self.widget)
        self.m_sonicV.setObjectName(_fromUtf8("m_sonicV"))
        self.horizontalLayout_9.addWidget(self.m_sonicV)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 4, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_13.addWidget(self.label_12)
        self.m_gainRange0Btn = QtGui.QRadioButton(self.widget)
        self.m_gainRange0Btn.setChecked(True)
        self.m_gainRange0Btn.setObjectName(_fromUtf8("m_gainRange0Btn"))
        self.horizontalLayout_13.addWidget(self.m_gainRange0Btn)
        self.m_gainRange1Btn = QtGui.QRadioButton(self.widget)
        self.m_gainRange1Btn.setObjectName(_fromUtf8("m_gainRange1Btn"))
        self.horizontalLayout_13.addWidget(self.m_gainRange1Btn)
        self.gridLayout.addLayout(self.horizontalLayout_13, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.m_sonicPD = QtGui.QDoubleSpinBox(self.widget)
        self.m_sonicPD.setObjectName(_fromUtf8("m_sonicPD"))
        self.horizontalLayout_5.addWidget(self.m_sonicPD)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.m_offset = QtGui.QDoubleSpinBox(self.widget)
        self.m_offset.setObjectName(_fromUtf8("m_offset"))
        self.horizontalLayout_6.addWidget(self.m_offset)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.m_triggerMode = QtGui.QComboBox(self.widget)
        self.m_triggerMode.setObjectName(_fromUtf8("m_triggerMode"))
        self.m_triggerMode.addItem(_fromUtf8(""))
        self.m_triggerMode.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.m_triggerMode)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.m_bandWidth = QtGui.QDoubleSpinBox(self.widget)
        self.m_bandWidth.setObjectName(_fromUtf8("m_bandWidth"))
        self.horizontalLayout_4.addWidget(self.m_bandWidth)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.m_prf = QtGui.QDoubleSpinBox(self.widget)
        self.m_prf.setObjectName(_fromUtf8("m_prf"))
        self.horizontalLayout_3.addWidget(self.m_prf)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.m_startSysBtn = QtGui.QPushButton(self.widget)
        self.m_startSysBtn.setObjectName(_fromUtf8("m_startSysBtn"))
        self.horizontalLayout_12.addWidget(self.m_startSysBtn)
        self.m_stopSysBtn = QtGui.QPushButton(self.widget)
        self.m_stopSysBtn.setObjectName(_fromUtf8("m_stopSysBtn"))
        self.horizontalLayout_12.addWidget(self.m_stopSysBtn)
        self.m_sendParaBtn = QtGui.QPushButton(self.widget)
        self.m_sendParaBtn.setObjectName(_fromUtf8("m_sendParaBtn"))
        self.horizontalLayout_12.addWidget(self.m_sendParaBtn)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)

        self.retranslateUi(ParaSetWidget)
        QtCore.QMetaObject.connectSlotsByName(ParaSetWidget)

    def retranslateUi(self, ParaSetWidget):
        ParaSetWidget.setWindowTitle(_translate("ParaSetWidget", "ParaSet", None))
        self.label.setText(_translate("ParaSetWidget", "通道选择", None))
        self.m_chanNo.setItemText(0, _translate("ParaSetWidget", "通道1", None))
        self.m_chanNo.setItemText(1, _translate("ParaSetWidget", "通道2", None))
        self.m_chanNo.setItemText(2, _translate("ParaSetWidget", "通道3", None))
        self.m_chanNo.setItemText(3, _translate("ParaSetWidget", "通道4", None))
        self.m_chanNo.setItemText(4, _translate("ParaSetWidget", "通道5", None))
        self.m_chanNo.setItemText(5, _translate("ParaSetWidget", "通道6", None))
        self.m_chanNo.setItemText(6, _translate("ParaSetWidget", "通道7", None))
        self.m_chanNo.setItemText(7, _translate("ParaSetWidget", "通道8", None))
        self.m_chanChecked.setText(_translate("ParaSetWidget", "通道使能", None))
        self.label_4.setText(_translate("ParaSetWidget", "激励电压", None))
        self.label_10.setText(_translate("ParaSetWidget", "采样个数", None))
        self.label_6.setText(_translate("ParaSetWidget", "增益", None))
        self.label_11.setText(_translate("ParaSetWidget", "接收通道", None))
        self.m_recvChanNo.setItemText(0, _translate("ParaSetWidget", "通道1", None))
        self.m_recvChanNo.setItemText(1, _translate("ParaSetWidget", "通道2", None))
        self.m_recvChanNo.setItemText(2, _translate("ParaSetWidget", "通道3", None))
        self.m_recvChanNo.setItemText(3, _translate("ParaSetWidget", "通道4", None))
        self.m_recvChanNo.setItemText(4, _translate("ParaSetWidget", "通道5", None))
        self.m_recvChanNo.setItemText(5, _translate("ParaSetWidget", "通道6", None))
        self.m_recvChanNo.setItemText(6, _translate("ParaSetWidget", "通道7", None))
        self.m_recvChanNo.setItemText(7, _translate("ParaSetWidget", "通道8", None))
        self.label_8.setText(_translate("ParaSetWidget", "声速", None))
        self.label_12.setText(_translate("ParaSetWidget", "增益范围", None))
        self.m_gainRange0Btn.setText(_translate("ParaSetWidget", "0-39(DB)", None))
        self.m_gainRange1Btn.setText(_translate("ParaSetWidget", "40-110(DB)", None))
        self.label_7.setText(_translate("ParaSetWidget", "声程", None))
        self.label_9.setText(_translate("ParaSetWidget", "起始偏移", None))
        self.label_2.setText(_translate("ParaSetWidget", "触发模式", None))
        self.m_triggerMode.setItemText(0, _translate("ParaSetWidget", "1", None))
        self.m_triggerMode.setItemText(1, _translate("ParaSetWidget", "2", None))
        self.label_5.setText(_translate("ParaSetWidget", "脉冲宽度", None))
        self.label_3.setText(_translate("ParaSetWidget", "重复频率", None))
        self.m_startSysBtn.setText(_translate("ParaSetWidget", "启动", None))
        self.m_stopSysBtn.setText(_translate("ParaSetWidget", "停止", None))
        self.m_sendParaBtn.setText(_translate("ParaSetWidget", "发送参数", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ParaSetWidget = QtGui.QWidget()
    ui = Ui_ParaSetWidget()
    ui.setupUi(ParaSetWidget)
    ParaSetWidget.show()
    sys.exit(app.exec_())

